// <auto-generated />
namespace NetworkBillingSystem_Alpha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seeddepartments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seeddepartments));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191538355_seed-departments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
