// <auto-generated />
namespace NetworkBillingSystem_Alpha.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clearedDataBase20170726 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clearedDataBase20170726));
        
        string IMigrationMetadata.Id
        {
            get { return "201707262242179_clearedDataBase20170726"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
